project:
  type: website
  output-dir: docs

website:
  title: "am-enright.github.io"
  navbar:
    background: success
    left:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full

#editor: visual

