---
name: Allison
surname: Enright
position: "Assistant Professor"
pronouns: she/her
address: "Department of Earth Sciences, University of New Brunswick"
phone: +1 506 447 3189
# www: allisoneright.ca
email: "allison.enright@unb.ca"
#twitter: mariecurie
#github: am-enright
#linkedin: https://www.linkedin.com/in/allison-enright/ #there is something in this url that's pissing of LaTeX
headcolor: "18BC9B"
date: "`r format(Sys.time(), '%B %Y')`"
knit: (function(inputFile, encoding) {
   rmarkdown::render(inputFile,
                    output_dir = "../docs",
                    knit_root_dir = rprojroot::find_rstudio_root_file())})
output:
  vitae::awesomecv: 
    page_total: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(here)
library(tibble)
library(readxl)
```

```{r make-readxl-function, include=FALSE}
readExcelSheets <- function(filename){ # read all sheets in .xlsx
all <- readxl::excel_sheets(filename) # import each sheet into a list using readxl::read_excel
list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x)) # save sheet name for each sheet (list)
names(list) <- all # breaks up list and creates a dataframe for each sheet with df names matching sheet names
list2env(list, envir = .GlobalEnv)
}
```

```{r import-xl, include=FALSE}
filename <- here::here("auto_cv_res",                        "enright_cv_input.xlsx")
readExcelSheets(filename)
```

# Test section

```{r test, include=FALSE}
# vitae::detailed_entries() # detailed_entries(data, what, when, with, where, why, .protect = TRUE)
# vitae::brief_entries() # brief_entries(data, what, when, with, .protect = TRUE)
```

# Education

```{r}
education %>% 
  detailed_entries(what = degree,
                   when = year,
                   with = institution,
                   where = where,
                   why = details)
#tribble(
#  ~ Degree, ~ Year, ~ Institution, ~ Where,
#  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
#  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
#  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
#) %>%
#  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

## 2n geaing

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Publications

```{r bibliography}
# use bibtex
bibliography_entries(here("auto_cv_res", "mypapers.bib")) # %>%
 # arrange() # complete this!!
```
